/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/web/**/*.{ts,tsx,html}'],
  theme: {
    extend: {
      colors: {
        paper: 'rgb(var(--color-paper) / <alpha-value>)',
        'paper-deep': 'rgb(var(--color-paper-deep) / <alpha-value>)',
        ink: 'rgb(var(--color-ink) / <alpha-value>)',
        'ink-soft': 'rgb(var(--color-ink-soft) / <alpha-value>)',
        line: 'rgb(var(--color-line) / <alpha-value>)',
        'line-strong': 'rgb(var(--color-line-strong) / <alpha-value>)',
        focus: 'rgb(var(--color-focus) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-soft': 'rgb(var(--color-accent-soft) / <alpha-value>)',
        danger: 'rgb(var(--color-danger) / <alpha-value>)',
        'danger-soft': 'rgb(var(--color-danger-soft) / <alpha-value>)',
        success: '#365b39',
        'green-100': '#f1f5f9',
        'green-600': '#cbd5e1',
        'green-800': '#334155',
        'green-900': '#475569',
        'gray-100': '#f9f6ee',
        'gray-200': '#f1ecdf',
        'gray-300': '#d7cfbf',
        'gray-700': '#5a5449',
        'gray-800': '#454038',
        'yellow-600': '#d4a574',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        tight: '0.125rem',
        '1.75': '0.4375rem',
        '2.25': '0.5625rem',
        '2.5': '0.625rem',
        '2.75': '0.6875rem',
        '3.25': '0.8125rem',
        '4.5': '1.125rem',
        '5': '1.25rem',
        '5.5': '1.375rem',
        '6.5': '1.625rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12.5': '3.125rem',
        '20': '5rem',
        '65': '16.25rem',
        '70': '17.5rem',
      },
      screens: {
        sm: '700px',
        md: '1060px',
      },
      fontFamily: {
        serif: ['Iowan Old Style', 'Palatino Linotype', 'Palatino', 'Times New Roman', 'serif'],
        sans: ['Avenir Next', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      fontSize: {
        '4xl': ['1rem', { lineHeight: '1.75' }],
        '5': ['1.25rem', { lineHeight: '1.3' }],
        '5.5': ['1.375rem', { lineHeight: '1.3' }],
        '6xl': ['clamp(1.875rem, 4vw, 2.625rem)', { lineHeight: '1.25' }],
      },
      borderRadius: {
        '2.5': '0.625rem',
        '3': '0.75rem',
      },
      lineHeight: {
        '1': '1',
        '1.5': '1.5',
        '1.6': '1.6',
        '1.75': '1.75',
        '1.9': '1.9',
        tight: '1.25',
      },
    },
  },
  plugins: [],
};
